version: "3.9"

services:
  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"
    networks:
      - rinha-net

  cache:
    image: redis:7.2-alpine
    hostname: cache
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "25MB"
    networks:
      - rinha-net

  api01: &api
    build: .
    hostname: api01
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_DATA_REDIS_HOST=cache
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    networks:
      - rinha-net
      - payment-processor

  api02:
    <<: *api
    hostname: api02


  lb:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres-data: